"use strict";

/* ============================================================================
   PART 6 — EXPORTS
   ============================================================================ */
function downloadReport() {
  const r = state.report;
  if (!r) return;
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const M = 48; let y = 56;

  doc.setFont('helvetica', 'bold').setFontSize(18).text('LabelLens compliance report', M, y);
  y += 18;
  doc.setFont('courier', 'normal').setFontSize(9).setTextColor(110)
     .text('Legal Metrology (Packaged Commodities) Rules, 2011', M, y);
  y += 26;

  doc.setTextColor(r.compliant ? 22 : 163, r.compliant ? 98 : 42, r.compliant ? 74 : 28);
  doc.setFont('helvetica', 'bold').setFontSize(15)
     .text(r.compliant ? 'COMPLIANT' : 'NON-COMPLIANT', M, y);
  y += 18;

  doc.setTextColor(40).setFont('courier', 'normal').setFontSize(9);
  [`Product   : ${r.product}`,
   `Report ID : ${r.id}`,
   `Checked   : ${r.checkedAt.toLocaleString('en-IN')} by ${r.checkedBy}`,
   `Result    : ${r.violations} violations, ${r.advisories} advisory, ${r.passed} passed`,
   `Min height: ${r.required.mm} mm (${r.required.band})`
  ].forEach(line => { doc.text(line, M, y); y += 13; });
  y += 10;

  doc.setDrawColor(200).line(M, y, 595 - M, y); y += 20;

  r.findings.forEach(f => {
    if (y > 760) { doc.addPage(); y = 56; }
    const mark = f.level === 'ok' ? '[ PASS ]' : f.level === 'warn' ? '[ NOTE ]' : '[ FAIL ]';
    doc.setFont('courier', 'bold').setFontSize(9)
       .setTextColor(...(f.level === 'ok' ? [22,98,74] : f.level === 'warn' ? [142,100,16] : [163,42,28]))
       .text(mark, M, y);
    doc.setTextColor(20).setFont('helvetica', 'bold').setFontSize(10)
       .text(doc.splitTextToSize(`${f.title}  (${f.cite})`, 420), M + 58, y);
    y += 13;
    doc.setFont('courier', 'normal').setFontSize(8.5).setTextColor(90);
    doc.splitTextToSize(sanitise(f.found), 440).forEach(l => { doc.text(l, M + 58, y); y += 11; });
    if (f.note) {
      doc.setTextColor(f.level === 'bad' ? 163 : 142, f.level === 'bad' ? 42 : 100, f.level === 'bad' ? 28 : 16);
      doc.splitTextToSize(f.note, 440).forEach(l => { doc.text(l, M + 58, y); y += 11; });
    }
    y += 8;
  });

  if (!r.compliant) {
    if (y > 700) { doc.addPage(); y = 56; }
    doc.setDrawColor(200).line(M, y, 595 - M, y); y += 18;
    doc.setFont('helvetica', 'normal').setFontSize(8.5).setTextColor(110);
    doc.splitTextToSize(
      'Penalty reference — Legal Metrology Act 2009, Sec. 36(1): fine up to Rs. 25,000 for a first ' +
      'offence, up to Rs. 50,000 for a second, and Rs. 50,000 to Rs. 1,00,000 or imprisonment up to ' +
      'one year, or both, for subsequent offences.', 500)
      .forEach(l => { doc.text(l, M, y); y += 11; });
  }

  doc.setFontSize(7.5).setTextColor(150)
     .text('Generated by LabelLens AI — prototype output, not a legal finding.', M, 810);
  doc.save(`${r.id}-${r.product.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.pdf`);
}

/* jsPDF core fonts are Latin-1, so swap the rupee sign before writing */
function sanitise(s) { return String(s).replace(/₹/g, 'Rs. ').replace(/[^\x20-\x7E]/g, ''); }
function escapeHtml(s) {
  return String(s).replace(/[&<>"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c]));
}

function copyFindings() {
  const r = state.report;
  const text = [`${r.compliant ? 'COMPLIANT' : 'NON-COMPLIANT'} — ${r.product} (${r.id})`, '']
    .concat(r.findings.map(f =>
      `${f.level === 'ok' ? 'PASS' : f.level === 'warn' ? 'NOTE' : 'FAIL'}  ${f.title} [${f.cite}]\n      ${f.found}${f.note ? '\n      ' + f.note : ''}`))
    .join('\n');
  navigator.clipboard.writeText(text).then(() => {
    const b = $('#copy'); const old = b.textContent;
    b.textContent = 'Copied'; setTimeout(() => b.textContent = old, 1400);
  });
}

/* ---- experience controls ---- */
function openScan(sample) {
  const scanTab = $('.tabs button[data-view="scan"]');
  scanTab.click();
  if (sample) loadSample(sample);
  setTimeout(() => $('#view-scan').scrollIntoView({ behavior: 'smooth', block: 'start' }), 40);
}

$('#heroScan').addEventListener('click', () => openScan('chips'));
$('#heroDemo').addEventListener('click', () => {
  openScan('oil');
  setTimeout(() => $('#run').click(), 450);
});

function animateHeroCounts() {
  $$('[data-count]').forEach(el => {
    const target = Number(el.dataset.count);
    const start = performance.now();
    const duration = 950;
    const tick = now => {
      const progress = Math.min((now - start) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      el.textContent = String(Math.round(target * eased)).padStart(2, '0');
      if (progress < 1) requestAnimationFrame(tick);
    };
    requestAnimationFrame(tick);
  });
}
animateHeroCounts();
